{
 "title": "dsmr",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "kiloWatt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current power usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:34",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:32",
       "field": "1-0:1.7.0",
       "id": "1",
       "inlineScript": "_value * 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000" } },
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "power usage 🔌",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Watt used",
     "bucketAggs": [
      {
       "$$hashKey": "object:90",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:88",
       "field": "1-0:1.7.0",
       "id": "1",
       "inlineScript": "_value * 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000" } },
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Watt generated",
     "bucketAggs": [
      {
       "$$hashKey": "object:90",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:88",
       "field": "1-0:2.7.0",
       "id": "1",
       "inlineScript": "_value * 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000" } },
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "current power generated",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:34",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:32",
       "field": "1-0:2.7.0",
       "id": "1",
       "inlineScript": "_value * 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000" } },
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Volt & Ampère", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Volt",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "L1 ",
     "bucketAggs": [
      {
       "$$hashKey": "object:462",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:460",
       "field": "1-0:32.7.0",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "L2",
     "bucketAggs": [
      {
       "$$hashKey": "object:462",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:460",
       "field": "1-0:52.7.0",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "L3",
     "bucketAggs": [
      {
       "$$hashKey": "object:462",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:460",
       "field": "1-0:72.7.0",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ampère",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "L1",
     "bucketAggs": [
      {
       "$$hashKey": "object:598",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:596",
       "field": "1-0:31.7.0",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "L2",
     "bucketAggs": [
      {
       "$$hashKey": "object:598",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:596",
       "field": "1-0:51.7.0",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "L3",
     "bucketAggs": [
      {
       "$$hashKey": "object:598",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:596",
       "field": "1-0:71.7.0",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "kWh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "total kWh used ☀️/🌙",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "watth" }
     ],
     "targets": [
      {
       "alias": "kWh☀️ (day)",
       "bucketAggs": [
        {
         "$$hashKey": "object:146",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:144",
         "field": "1-0:1.8.1",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "@timestamp"
      },
      {
       "alias": "kWh🌙 (night)",
       "bucketAggs": [
        {
         "$$hashKey": "object:146",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$interval", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:144",
         "field": "1-0:1.8.2",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "kWh / day",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:390",
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:388",
         "field": "1-0:1.7.0",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}